version: '3'
services:
  mongo:
    image: mongo:3.2
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
  app:
    image: georgiyolovski/fifa-api
    ports:
      - "4000:4000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - DB_NAME=fifaApp
      - DB_HOST=mongo
      - DB_PORT=27017
volumes:
  mongo-data: